### ISSUE TITLE
OS X Yosemite Install

### ISSUE THREAD

**Issue by mrado1** [gurgeh/selfspy#118]
I've followed the directions for install, and I'm getting back this when I try to run selfspy:

Michaels-MacBook-Pro:selfspy michaelrado$ selfspy --help
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/selfspy", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources.py", line 2880, in <module>
    working_set = WorkingSet._build_master()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources.py", line 432, in _build_master
    ws.require(__requires__)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources.py", line 741, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources.py", line 626, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pyobjc-framework-Quartz==3.0.1

I ran sudo easy_install -U pyobjc-core and it seemed to be successful... Any help here, please?

**Comment by ype** [comment]
can you run the following three commands to give a little more information - this will help fix the issue.

When I run, `python -V`, `which python` and `pip list` in my selfspy virtualenv the output is as follows:

```bash
$ python -V
Python 2.7.9
```

```bash
which python
/Users/anton/.virtualenvs/selfspy/bin/python
```

```bash
$ pip list
keyring (1.2.2)
lockfile (0.9.1)
mutagen (1.27)
pip (1.5.6)
pycrypto (2.5)
pyobjc-core (3.0.4)
pyobjc-framework-Cocoa (3.0.4)
pyobjc-framework-CoreLocation (3.0.4)
pyobjc-framework-LaunchServices (3.0.4)
pyobjc-framework-Quartz (3.0.4)
setuptools (3.6)
SQLAlchemy (0.9.4)
wsgiref (0.1.2)
```

**Comment by mrado1** [comment]
Hi, thanks for the quick response! Here's the info as requested:

```
Michaels-MacBook-Pro:selfspy michaelrado$ python -V
Python 2.7.9
```

```
Michaels-MacBook-Pro:selfspy michaelrado$ which python
/Library/Frameworks/Python.framework/Versions/2.7/bin/python
```

```
Michaels-MacBook-Pro:selfspy michaelrado$ pip list
altgraph (0.12)
keyring (5.3)
lockfile (0.10.2)
macholib (1.7)
modulegraph (0.12)
pip (1.5.6)
py2app (0.9)
pycrypto (2.6.1)
pyobjc (3.0.4)
pyobjc-core (3.0.4)
pyobjc-framework-Accounts (3.0.4)
pyobjc-framework-AddressBook (3.0.4)
pyobjc-framework-AppleScriptKit (3.0.4)
pyobjc-framework-AppleScriptObjC (3.0.4)
pyobjc-framework-Automator (3.0.4)
pyobjc-framework-CalendarStore (3.0.4)
pyobjc-framework-CFNetwork (3.0.4)
pyobjc-framework-Cocoa (3.0.4)
pyobjc-framework-Collaboration (3.0.4)
pyobjc-framework-CoreData (3.0.4)
pyobjc-framework-CoreLocation (3.0.4)
pyobjc-framework-CoreText (3.0.4)
pyobjc-framework-CoreWLAN (3.0.4)
pyobjc-framework-DictionaryServices (3.0.4)
pyobjc-framework-DiskArbitration (3.0.4)
pyobjc-framework-EventKit (3.0.4)
pyobjc-framework-ExceptionHandling (3.0.4)
pyobjc-framework-FSEvents (3.0.4)
pyobjc-framework-InputMethodKit (3.0.4)
pyobjc-framework-InstallerPlugins (3.0.4)
pyobjc-framework-InstantMessage (3.0.4)
pyobjc-framework-LatentSemanticMapping (3.0.4)
pyobjc-framework-LaunchServices (3.0.4)
pyobjc-framework-PreferencePanes (3.0.4)
pyobjc-framework-PubSub (3.0.4)
pyobjc-framework-QTKit (3.0.4)
pyobjc-framework-Quartz (3.0.4)
pyobjc-framework-ScreenSaver (3.0.4)
pyobjc-framework-ScriptingBridge (3.0.4)
pyobjc-framework-SearchKit (3.0.4)
pyobjc-framework-ServiceManagement (3.0.4)
pyobjc-framework-Social (3.0.4)
pyobjc-framework-StoreKit (3.0.4)
pyobjc-framework-SyncServices (3.0.4)
pyobjc-framework-SystemConfiguration (3.0.4)
pyobjc-framework-WebKit (3.0.4)
selfspy (0.3.0)
setuptools (7.0)
SQLAlchemy (0.9.9)
wsgiref (0.1.2)
```

**Comment by ype** [comment]
from what i can see your problem may be stemming from one of pythons more fiddly qualities - it doesn't like being run as root all to much

Rather then installing to your global/root python you may want to try installing to a virtualenv - I ran into several similar errors when first trying to install selfspy using the root python rather then a python virtual environment

Also, using `sudo easy_install some-package` or `sudo python install setup.py` is can create more pain then pleasure as python isn't a fan of sudo and global installs - a lot of can break - installing to user rather then root is a much safer and less error prone alternative - although with selfspy this isn't doesn't work as root access is needed.

when I built mine I ended up building the binaries in a virtual environment then aliasing them to `/usr/opt`

A good place to start would be doing a fresh install of selfspy in a virtualenv to narrow down the problem. if you are new to virtualenvs here is a good tutorial: [Virtual Environments](http://docs.python-guide.org/en/latest/dev/virtualenvs/)

also what version of OSX are you on? if your using OSX 10.10 and want to record keystrokes you'll need [jacobsalmela/tccutil](https://github.com/jacobsalmela/tccutil)

**Comment by mrado1** [comment]
Okay thank you for the help. I tried to install a virtual environment using the steps in http://docs.python-guide.org/en/latest/dev/virtualenvs/, and then went through the selfspy steps here: https://github.com/benzguo/qself/blob/master/selfspy.md.

Sorry if this is like arranging deck chairs on the Titanic. Here are my exact steps below:

```
$ pip install virtualenv
```

```
$ cd DigitalLabor
```

```
$ virtualenv digitallabor
```

```
$ source digitallabor/bin/activate
```

```
$ cd digitallabor
```

```
$ git clone git://github.com/gurgeh/selfspy
```

```
$ cd selfspy
```

```
$ sudo easy_install - U pyobjc-core
```	
Series of errors and warnings, but says installed…

```
$ sudo python setup.py install
```

```
$ curl https://raw.github.com/benzguo/qself/master/com.github.selfspy.plist > ~/Library/LaunchAgents/com.github.selfspy.plist
```
Does this need to be somewhere else because of the virtualenv? After this command, there isn’t a com.github.selfspy.plist in the LaunchAgents folder.

Logged out and logged back in.

```
$ source digitallabor/bin/activate
```

```
$ selfstats --pactive
```

```
pkg_resources.DistributionNotFound: pyobjc-framework-Quartz==3.0.1
```

```
$ sudo easy_install -U pyobjc-core==3.0.1
```
Wingin’ it here.

Logged out and logged back in.

```
$ source digitallabor/bin/activate
```

```
selfstats --pactive
```

```
pkg_resources.DistributionNotFound: pyobjc-framework-Quartz==3.0.1
```

Forgot to install tccutil.

```
$ cd digitallabor
```

```
$ git clone git://github.com/jacobsalmela/tccutil
```

```
$ cd tccutil
```

```
$ sudo python tccutil.py install
```
Asks for password, no feedback after, clearly missing something here.

Logged out and logged back in.

```
$ source digitallabor/bin/activate
```

```
selfstats --pactive
```

```
pkg_resources.DistributionNotFound: pyobjc-framework-Quartz==3.0.1
```
This is the same error as my original post, I’m just not pasting it all.

**Comment by ype** [comment]
so python is getting annoyed with the pyobjc - which is not an uncommon issue...it might be worth checking out the issues on https://bitbucket.org/ronaldoussoren/pyobjc - there are a few issues that are closed that address this issue - also you shouldn't run `sudo easy_install -U` in your virtualenv as it is an isolated python environment created for/by you

I am running selfspy with `pyobjc-core==3.0.4` which is working fine - you may also wanna just try a straight `pip install pyobjc-core` and see how that goes - sorry the answer isn't a simple one - selfspy and the past few versions of osx don't play nice together easily...might be time for an osx specific fork of selfspy if @gurgeh doesn't mind

**Comment by mrado1** [comment]
Did you have to modify anything for selfspy to recognize 3.0.4? It looks like it's continuously checking for 3.0.1. Does that question even make sense?

**Comment by spbrien** [comment]
I was able to install on 10.10 by updating osx-requirements.txt to the following:
```
SQLAlchemy==0.9.4
lockfile==0.9.1
pycrypto==2.5
pyobjc-core==3.0.4
pyobjc-framework-Cocoa==3.0.4
keyring==1.2.2
pyobjc-framework-Quartz==3.0.4
```

**Comment by perelin** [comment]
Had the same problem. @spbrien solution worked for me. Pull request and updated file here: https://github.com/gurgeh/selfspy/pull/122

**Comment by perelin** [comment]
Another thing though: does anyone know how to add the selfspy binary (/usr/local/bin/selfspy) to the list of apps that can control the computer in `System Preferences > Security > Privacy > Accessibility` as suggested in the `README.me`?

**Comment by mrado1** [comment]
Yes, that worked! I had tried to install just the requirements with ```$ pip install -r osx-requirements.txt```, but realized I needed to reinstall selfspy with the new new reqs.

As far as the selfspy binary, ype suggested installing <a href="https://github.com/jacobsalmela/tccutil">jacobsalmela/tccutil</a>, which I did, and added both ```/usr/local/bin/python2.7``` and ```/usr/local/share/python/selfspy``` (well, actually the folder where my selfspy binary is located).

When I run ```selfstats --clicks``` for example, selfstats returns a number of clicks, but it doesn't increase in realtime, so it doesn't appear that selfspy is launching automatically after I log back in.

**Comment by spbrien** [comment]
@mrado1, I've had a very hard time getting this to launch at boot with launchd. At first I thought it was an issue with the Tkinter dialogue box (I think I solved that issue w/ the changes in pull request #120), but after fixing that, I still can't get it to launch correctly.

**Comment by perelin** [comment]
@spbrien Thanks, I got it running using tccutil. Now launch-on-startup is the next issue. 

Right I´m just launching in manually with `nohup selfspy &` to get it running in the background. Does anyone know if there is a better way to have it running in the background?
