### ISSUE TITLE
Setup script fails on OS X 10.10

### ISSUE THREAD

**Issue by eproxus** [gurgeh/selfspy#123]
Using Python 2.7.9 installed via Homebrew (`brew install python --with-brewed-tk`) on OS X 10.10.2, I get an error while trying to install Selfspy.

I'm have installed the following `requirements.txt` with `pip install -U -r requirements.txt` as suggested in #118 (https://github.com/gurgeh/selfspy/issues/118#issuecomment-83123484):
```python
SQLAlchemy==0.9.4
lockfile==0.9.1
pycrypto==2.5
pyobjc-core==3.0.4
pyobjc-framework-Cocoa==3.0.4
keyring==1.2.2
pyobjc-framework-Quartz==3.0.4
```

When running the install script, the following error occurs:
```
$ python setup.py install
"['SQLAlchemy==0.9.4\n', 'lockfile==0.9.1\n', 'pycrypto==2.5\n', 'pyobjc-core==3.0.1\n', 'pyobjc-framework-Cocoa==3.0.1\n', 'keyring==1.2.2\n', 'pyobjc-framework-Quartz==3.0.1\n']"
running install
running bdist_egg
running egg_info
writing requirements to selfspy.egg-info/requires.txt
writing selfspy.egg-info/PKG-INFO
writing top-level names to selfspy.egg-info/top_level.txt
writing dependency_links to selfspy.egg-info/dependency_links.txt
writing entry points to selfspy.egg-info/entry_points.txt
writing pbr to selfspy.egg-info/pbr.json
reading manifest file 'selfspy.egg-info/SOURCES.txt'
writing manifest file 'selfspy.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.10-x86_64/egg
running install_lib
running build_py
creating build/bdist.macosx-10.10-x86_64/egg
creating build/bdist.macosx-10.10-x86_64/egg/selfspy
copying build/lib/selfspy/__init__.py -> build/bdist.macosx-10.10-x86_64/egg/selfspy
copying build/lib/selfspy/activity_store.py -> build/bdist.macosx-10.10-x86_64/egg/selfspy
copying build/lib/selfspy/check_password.py -> build/bdist.macosx-10.10-x86_64/egg/selfspy
copying build/lib/selfspy/config.py -> build/bdist.macosx-10.10-x86_64/egg/selfspy
copying build/lib/selfspy/models.py -> build/bdist.macosx-10.10-x86_64/egg/selfspy
copying build/lib/selfspy/password_dialog.py -> build/bdist.macosx-10.10-x86_64/egg/selfspy
copying build/lib/selfspy/period.py -> build/bdist.macosx-10.10-x86_64/egg/selfspy
copying build/lib/selfspy/sniff_cocoa.py -> build/bdist.macosx-10.10-x86_64/egg/selfspy
copying build/lib/selfspy/sniff_win.py -> build/bdist.macosx-10.10-x86_64/egg/selfspy
copying build/lib/selfspy/sniff_x.py -> build/bdist.macosx-10.10-x86_64/egg/selfspy
copying build/lib/selfspy/stats.py -> build/bdist.macosx-10.10-x86_64/egg/selfspy
byte-compiling build/bdist.macosx-10.10-x86_64/egg/selfspy/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.10-x86_64/egg/selfspy/activity_store.py to activity_store.pyc
byte-compiling build/bdist.macosx-10.10-x86_64/egg/selfspy/check_password.py to check_password.pyc
byte-compiling build/bdist.macosx-10.10-x86_64/egg/selfspy/config.py to config.pyc
byte-compiling build/bdist.macosx-10.10-x86_64/egg/selfspy/models.py to models.pyc
byte-compiling build/bdist.macosx-10.10-x86_64/egg/selfspy/password_dialog.py to password_dialog.pyc
byte-compiling build/bdist.macosx-10.10-x86_64/egg/selfspy/period.py to period.pyc
byte-compiling build/bdist.macosx-10.10-x86_64/egg/selfspy/sniff_cocoa.py to sniff_cocoa.pyc
byte-compiling build/bdist.macosx-10.10-x86_64/egg/selfspy/sniff_win.py to sniff_win.pyc
byte-compiling build/bdist.macosx-10.10-x86_64/egg/selfspy/sniff_x.py to sniff_x.pyc
byte-compiling build/bdist.macosx-10.10-x86_64/egg/selfspy/stats.py to stats.pyc
creating build/bdist.macosx-10.10-x86_64/egg/EGG-INFO
copying selfspy.egg-info/PKG-INFO -> build/bdist.macosx-10.10-x86_64/egg/EGG-INFO
copying selfspy.egg-info/SOURCES.txt -> build/bdist.macosx-10.10-x86_64/egg/EGG-INFO
copying selfspy.egg-info/dependency_links.txt -> build/bdist.macosx-10.10-x86_64/egg/EGG-INFO
copying selfspy.egg-info/entry_points.txt -> build/bdist.macosx-10.10-x86_64/egg/EGG-INFO
copying selfspy.egg-info/pbr.json -> build/bdist.macosx-10.10-x86_64/egg/EGG-INFO
copying selfspy.egg-info/requires.txt -> build/bdist.macosx-10.10-x86_64/egg/EGG-INFO
copying selfspy.egg-info/top_level.txt -> build/bdist.macosx-10.10-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/selfspy-0.3.0-py2.7.egg' and adding 'build/bdist.macosx-10.10-x86_64/egg' to it
removing 'build/bdist.macosx-10.10-x86_64/egg' (and everything under it)
Processing selfspy-0.3.0-py2.7.egg
Removing /usr/local/lib/python2.7/site-packages/selfspy-0.3.0-py2.7.egg
Copying selfspy-0.3.0-py2.7.egg to /usr/local/lib/python2.7/site-packages
selfspy 0.3.0 is already the active version in easy-install.pth
Installing selfstats script to /usr/local/bin
Installing selfspy script to /usr/local/bin

Installed /usr/local/lib/python2.7/site-packages/selfspy-0.3.0-py2.7.egg
Processing dependencies for selfspy==0.3.0
Searching for pyobjc-framework-Quartz==3.0.1
Reading https://pypi.python.org/simple/pyobjc-framework-Quartz/
/usr/local/lib/python2.7/site-packages/setuptools-12.0.5-py2.7.egg/pkg_resources/__init__.py:2510: PEP440Warning: 'pyobjc (framework-Quartz-2.2)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
/usr/local/lib/python2.7/site-packages/setuptools-12.0.5-py2.7.egg/pkg_resources/__init__.py:2510: PEP440Warning: 'pyobjc-framework (Quartz-2.2)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
/usr/local/lib/python2.7/site-packages/setuptools-12.0.5-py2.7.egg/pkg_resources/__init__.py:2510: PEP440Warning: 'pyobjc (framework-Quartz-2.2b1)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
/usr/local/lib/python2.7/site-packages/setuptools-12.0.5-py2.7.egg/pkg_resources/__init__.py:2510: PEP440Warning: 'pyobjc-framework (Quartz-2.2b1)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
/usr/local/lib/python2.7/site-packages/setuptools-12.0.5-py2.7.egg/pkg_resources/__init__.py:2510: PEP440Warning: 'pyobjc (framework-Quartz-2.2b2)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
/usr/local/lib/python2.7/site-packages/setuptools-12.0.5-py2.7.egg/pkg_resources/__init__.py:2510: PEP440Warning: 'pyobjc-framework (Quartz-2.2b2)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
/usr/local/lib/python2.7/site-packages/setuptools-12.0.5-py2.7.egg/pkg_resources/__init__.py:2510: PEP440Warning: 'pyobjc (framework-Quartz-2.3)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
/usr/local/lib/python2.7/site-packages/setuptools-12.0.5-py2.7.egg/pkg_resources/__init__.py:2510: PEP440Warning: 'pyobjc-framework (Quartz-2.3)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
/usr/local/lib/python2.7/site-packages/setuptools-12.0.5-py2.7.egg/pkg_resources/__init__.py:2510: PEP440Warning: 'pyobjc (framework-Quartz-2.4)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
/usr/local/lib/python2.7/site-packages/setuptools-12.0.5-py2.7.egg/pkg_resources/__init__.py:2510: PEP440Warning: 'pyobjc-framework (Quartz-2.4)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
/usr/local/lib/python2.7/site-packages/setuptools-12.0.5-py2.7.egg/pkg_resources/__init__.py:2510: PEP440Warning: 'pyobjc (framework-Quartz-2.5.1)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
/usr/local/lib/python2.7/site-packages/setuptools-12.0.5-py2.7.egg/pkg_resources/__init__.py:2510: PEP440Warning: 'pyobjc-framework (Quartz-2.5.1)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
/usr/local/lib/python2.7/site-packages/setuptools-12.0.5-py2.7.egg/pkg_resources/__init__.py:2510: PEP440Warning: 'pyobjc (framework-Quartz-3.0.1)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
/usr/local/lib/python2.7/site-packages/setuptools-12.0.5-py2.7.egg/pkg_resources/__init__.py:2510: PEP440Warning: 'pyobjc-framework (Quartz-3.0.1)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
/usr/local/lib/python2.7/site-packages/setuptools-12.0.5-py2.7.egg/pkg_resources/__init__.py:2510: PEP440Warning: 'pyobjc (framework-Quartz-3.0.3)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
/usr/local/lib/python2.7/site-packages/setuptools-12.0.5-py2.7.egg/pkg_resources/__init__.py:2510: PEP440Warning: 'pyobjc-framework (Quartz-3.0.3)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
/usr/local/lib/python2.7/site-packages/setuptools-12.0.5-py2.7.egg/pkg_resources/__init__.py:2510: PEP440Warning: 'pyobjc (framework-Quartz-3.0.4)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
/usr/local/lib/python2.7/site-packages/setuptools-12.0.5-py2.7.egg/pkg_resources/__init__.py:2510: PEP440Warning: 'pyobjc-framework (Quartz-3.0.4)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
Best match: pyobjc-framework-Quartz 3.0.1
Downloading https://pypi.python.org/packages/source/p/pyobjc-framework-Quartz/pyobjc-framework-Quartz-3.0.1.tar.gz#md5=9fb36fe671976b78048bd14e0b3813f5
Processing pyobjc-framework-Quartz-3.0.1.tar.gz
Writing /var/folders/hl/5nvrk2bj40q1gvw6b301lx500000gn/T/easy_install-RxI1TB/pyobjc-framework-Quartz-3.0.1/setup.cfg
Running pyobjc-framework-Quartz-3.0.1/setup.py -q bdist_egg --dist-dir /var/folders/hl/5nvrk2bj40q1gvw6b301lx500000gn/T/easy_install-RxI1TB/pyobjc-framework-Quartz-3.0.1/egg-dist-tmp-B3oxir
warning: no directories found matching 'source-deps'
warning: no previously-included files matching '.DS_Store' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
Traceback (most recent call last):
  File "setup.py", line 32, in <module>
    'selfstats=selfspy.stats:main']))
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.macosx-10.10-x86_64/egg/setuptools/command/install.py", line 67, in run
  File "build/bdist.macosx-10.10-x86_64/egg/setuptools/command/install.py", line 117, in do_egg_install
  File "build/bdist.macosx-10.10-x86_64/egg/setuptools/command/easy_install.py", line 374, in run

  File "build/bdist.macosx-10.10-x86_64/egg/setuptools/command/easy_install.py", line 604, in easy_install

  File "build/bdist.macosx-10.10-x86_64/egg/setuptools/command/easy_install.py", line 655, in install_item

  File "build/bdist.macosx-10.10-x86_64/egg/setuptools/command/easy_install.py", line 703, in process_distribution

  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources/__init__.py", line 797, in resolve

  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources/__init__.py", line 1047, in best_match

  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources/__init__.py", line 1059, in obtain

  File "build/bdist.macosx-10.10-x86_64/egg/setuptools/command/easy_install.py", line 623, in easy_install

  File "build/bdist.macosx-10.10-x86_64/egg/setuptools/command/easy_install.py", line 653, in install_item

  File "build/bdist.macosx-10.10-x86_64/egg/setuptools/command/easy_install.py", line 838, in install_eggs

  File "build/bdist.macosx-10.10-x86_64/egg/setuptools/command/easy_install.py", line 1066, in build_and_install

  File "build/bdist.macosx-10.10-x86_64/egg/setuptools/command/easy_install.py", line 1052, in run_setup

  File "build/bdist.macosx-10.10-x86_64/egg/setuptools/sandbox.py", line 238, in run_setup
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "build/bdist.macosx-10.10-x86_64/egg/setuptools/sandbox.py", line 191, in setup_context
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "build/bdist.macosx-10.10-x86_64/egg/setuptools/sandbox.py", line 162, in save_modules
  File "build/bdist.macosx-10.10-x86_64/egg/setuptools/sandbox.py", line 137, in resume
  File "build/bdist.macosx-10.10-x86_64/egg/setuptools/sandbox.py", line 150, in save_modules
  File "build/bdist.macosx-10.10-x86_64/egg/setuptools/sandbox.py", line 191, in setup_context
  File "build/bdist.macosx-10.10-x86_64/egg/setuptools/sandbox.py", line 235, in run_setup
  File "build/bdist.macosx-10.10-x86_64/egg/setuptools/sandbox.py", line 265, in run
  File "build/bdist.macosx-10.10-x86_64/egg/setuptools/sandbox.py", line 234, in runner
  File "build/bdist.macosx-10.10-x86_64/egg/setuptools/sandbox.py", line 46, in _execfile
  File "/var/folders/hl/5nvrk2bj40q1gvw6b301lx500000gn/T/easy_install-RxI1TB/pyobjc-framework-Quartz-3.0.1/setup.py", line 80, in <module>

  File "/var/folders/hl/5nvrk2bj40q1gvw6b301lx500000gn/T/easy_install-RxI1TB/pyobjc-framework-Quartz-3.0.1/pyobjc_setup.py", line 461, in setup
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.macosx-10.10-x86_64/egg/setuptools/command/bdist_egg.py", line 161, in run
  File "build/bdist.macosx-10.10-x86_64/egg/setuptools/command/bdist_egg.py", line 147, in call_command
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.macosx-10.10-x86_64/egg/setuptools/command/install_lib.py", line 11, in run
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install_lib.py", line 115, in install
    outfiles = self.copy_tree(self.build_dir, self.install_dir)
  File "build/bdist.macosx-10.10-x86_64/egg/setuptools/command/install_lib.py", line 88, in copy_tree
  File "/var/folders/hl/5nvrk2bj40q1gvw6b301lx500000gn/T/easy_install-RxI1TB/pyobjc-framework-Quartz-3.0.1/pyobjc_setup.py", line 204, in get_exclusions
TypeError: 'set' object does not support item assignment
```

**Comment by ype** [comment]
you might want to double check your installed libraries as setup.py is still looking erroring on the fact it is trying to install `pyobjc-framework-Quartz==3.0.1`

a few possibilities of why this could be happen are: 
you have tried to install selfspy before and it added the `pyobjc-framework-Quartz==3.0.1` in which case you could attempt to upgrade it using `pip install -U pyobjc-framework-Quartz==3.0.4` or `pip install --force-reinstall pyobjc-framework-Quartz==3.0.4`

alternatively, if this is your first install of selfspy double check to make sure that you are referencing the correct requirements text and are using @perelin's fork [perelin/selfspy](https://github.com/perelin/selfspy) which has the updated `osx-requirements.txt`

**Comment by kevinjalbert** [comment]
I had this exact problem and the suggestion of using @perelin's fork solved it form me.

Looks like we have two PRs which solves this currently open (#122 and #119).

**Comment by gurgeh** [comment]
I have now merged this PR
