### ISSUE TITLE
 'ascii' codec can't encode character 

### ISSUE THREAD

**Issue by lordnynex** [gurgeh/selfspy#133]
Traceback (most recent call last):
  File "/usr/local/bin/selfspy", line 9, in <module>
    load_entry_point('selfspy==0.3.0', 'console_scripts', 'selfspy')()
  File "build/bdist.linux-x86_64/egg/selfspy/__init__.py", line 139, in main
  File "build/bdist.linux-x86_64/egg/selfspy/activity_store.py", line 99, in run
  File "build/bdist.linux-x86_64/egg/selfspy/sniff_x.py", line 86, in run
  File "/usr/lib/python2.7/dist-packages/Xlib/ext/record.py", line 238, in enable_context
    context = context)
  File "/usr/lib/python2.7/dist-packages/Xlib/ext/record.py", line 215, in __init__
    rq.ReplyRequest.__init__(self, *args, **keys)
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/rq.py", line 1478, in __init__
    self.reply()
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/rq.py", line 1490, in reply
    self._display.send_and_recv(request = self._serial)
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/display.py", line 556, in send_and_recv
    gotreq = self.parse_response(request)
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/display.py", line 643, in parse_response
    gotreq = self.parse_request_response(request) or gotreq
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/display.py", line 729, in parse_request_response
    req._parse_response(self.data_recv[:self.request_length])
  File "/usr/lib/python2.7/dist-packages/Xlib/ext/record.py", line 219, in _parse_response
    self._callback(r)
  File "build/bdist.linux-x86_64/egg/selfspy/sniff_x.py", line 104, in processevents
  File "build/bdist.linux-x86_64/egg/selfspy/sniff_x.py", line 197, in get_cur_window
  File "build/bdist.linux-x86_64/egg/selfspy/sniff_x.py", line 181, in get_wm_name
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 18: ordinal not in range(128)

**Comment by lordnynex** [comment]
I have absolutely no clue whats wrong here. I was adding some debug statements to figure out whats going on. 

I ran:
```
sudo rm /usr/local/lib/python2.7/dist-packages/selfspy-0.3.0-py2.7.egg
sudo python setup.py install
```

and now it works. strange

**Comment by aDrz** [comment]
I try your way however I still have this problem. This error occurred every time a special character appears in google chrome title !

**Comment by aDrz** [comment]
Well I think I kind of solve the problem by changing the line 181 of sniff_x.py by,

> return d.value.encode('utf-8').decode('utf-8')

I still struggle with encoding/decoding string in python.

**Comment by dfaerch** [comment]
I'm having this as well. After playing around with this for an hour or so, my guess is, that

    win.get_full_property(self.atom_NET_WM_NAME, self.atom_UTF8_STRING)

(line 175) doesnt actually return UTF8, even though instructed to. Maybe its a distro specific bug? Maybe Ubuntu + Unity is forgetting to honor encoding request? I'm just guessing here.
I run Ubuntu 12.04 with Unity.

Anyway, extending on @aDrz solution, which works fine, i suggest a patch, like this:
```patch
--- a/selfspy/sniff_x.py
+++ b/selfspy/sniff_x.py
@@ -178,7 +178,10 @@ class Sniffer:
             if r:
                 return r.decode('latin1')  # WM_NAME with type=STRING.
         else:
-            return d.value.decode('utf8')
+            try:
+                return d.value.decode('utf-8')
+            except UnicodeError:
+                return d.value.encode('utf-8').decode('utf-8')
 
     def get_cur_window(self):
         i = 0
```

This fixes the problem, without messing up the original functionality.

**Comment by aDrz** [comment]
Thank you !

As @dfaerch said, it seems to be a specific Ubuntu error. However, I am on Ubuntu 14.04 without Unity.

**Comment by jots** [comment]
I had the same problem on ubuntu 14.04.  I have added @dfaerch's patch and running again.

**Comment by olejorgenb** [comment]
I also got this in my .xsession-error a while back. The actual error isn't timestamped, but judging by nearby stamped entries it seems to coincident with when my selfspy process randomly died. (didn't notice it before a couple weeks :()

So regardless of the actual bug, the process should definitively not die.

This is on arch linux so it's not ubuntu specific.
