### ISSUE TITLE
OSX 10.12 Installation

### ISSUE THREAD

**Issue by exentropie** [gurgeh/selfspy#151]
Hey,

I'm having troubles getting selfspy to run on OSX 10.12.3.

First problem started with installing the OSX requirements. I think the culprit here was trying to install the old "pyobjc" dependencies, which always caused some errors. I manually downloaded "pyobjc-3.2.2b1" and was able to successfully install it. 
From there I updated the "osx-requirements.txt" and installed selfspy. 

Right now I'm struggling with selfspy to actually store some information. When I run "$ selfstats -pactive" I get:

```
<RowID> <Starting date and time> <Duration> <Process> <Window title> <Number of keys pressed>
0 rows
```

The output of "$ selfspy" is:

```
/Users/xy/.selfspy/selfspy.pid is locked! I am probably already running.
If you can find no selfspy process running, it is a stale lock and you can safely remove it.
Shutting down.
```

Maybe the reason is enabling the "access for assistive devices", but I don't know exactly how to do this. Using "https://github.com/jacobsalmela/tccutil" doesn't seem to work anymore with OSX 10.12.

I hope someone got selfspy running under OSX 10.12 and can help me out.

Regards!

**Comment by exentropie** [comment]
The first time after a new install of the dependencies and selfspy and starting "$ selfspy" I get:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/selfspy", line 11, in <module>
    load_entry_point('selfspy==0.3.0', 'console_scripts', 'selfspy')()
  File "build/bdist.macosx-10.6-intel/egg/selfspy/__init__.py", line 139, in main
  File "build/bdist.macosx-10.6-intel/egg/selfspy/activity_store.py", line 99, in run
  File "build/bdist.macosx-10.6-intel/egg/selfspy/sniff_cocoa.py", line 93, in run
  File "build/bdist.macosx-10.6-intel/egg/selfspy/sniff_cocoa.py", line 57, in createAppDelegate
objc.BadPrototypeError: Objective-C expects 1 arguments, Python argument has 2 arguments for <unbound selector applicationWillResignActive of AppDelegate at 0x106566168>
```

At this point something is going wrong already.

**Comment by tnorthcutt** [comment]
Same problem here. I understand how to give apps Accessibility permissions, but selfspy is not present in the list under System Preferences > Privacy > Accessibility.

**Comment by marcdk** [comment]
Hi Guys, did anyone manage to figure out how to add selfspy to the list under System Preferences > Privacy > Accessibility?

**Comment by exentropie** [comment]
Hey, unfortunately not. Sorry!

Marc de Klerk schrieb:

**Comment by antiDigest** [comment]
Still unable to solve this problem ? I need a solution. I have two systems, one a newer mac, other an older one. Selfspy runs perfectly fine on the new system, while giving this exact error on older mac.

Note: I have not yet installed the app on the older mac, have been attempting to run it as
```python selfspy/__init__.py```

It is installed on the newer mac and just needs the accessibility permission to be able to run at startup.

**Comment by antiDigest** [comment]
It seems like the problem is associated to installing python2 via Homebrew. I've been circling among 3 types of errors which don't get solved.
