### ISSUE TITLE
cannot import name LockFile

### ISSUE THREAD

**Issue by byorgey** [gurgeh/selfspy#88]
Most likely this is some problem with my setup rather than a problem with selfspy per se, but I've Googled and such to no avail, and I'm hoping someone can tell me what's going on.

```
$ selfspy
Traceback (most recent call last):
  File "/usr/bin/selfspy", line 26, in <module>
    from lockfile import LockFile
ImportError: cannot import name LockFile
```

Here's my environment:

```
$ python --version
Python 2.7.4
$ uname -a
Linux reedrosenbluth-Gazelle-Professional 3.8.0-34-generic #49-Ubuntu SMP Tue Nov 12 18:00:10 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
$ dpkg --get-selections | grep lockfile
liblockfile-bin                 install
liblockfile1:amd64              install
lockfile-progs                  install
python-lockfile                 install
$ cd src/selfspy
$ git rev-parse HEAD
dad9a433e2a798935be11edaf4bdd6f5881b52f5
```

**Comment by hontvari** [comment]
I have got the same error. After
```
sudo apt-get install python-pip python-tk git subversion
git clone git://github.com/gurgeh/selfspy
cd selfspy/
sudo pip install svn+https://python-xlib.svn.sourceforge.net/svnroot/python-xlib/tags/xlib_0_15rc1/
sudo pip install SQLAlchemy lockfile pycrypto keyring
sudo pip install --upgrade lockfile
sudo make install
sudo python setup.py install
```
I still get a similar error:
```
$ sudo selfspy
Traceback (most recent call last):
  File "/usr/local/bin/selfspy", line 9, in <module>
    load_entry_point('selfspy==0.3.0', 'console_scripts', 'selfspy')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "build/bdist.linux-x86_64/egg/selfspy/__init__.py", line 26, in <module>
ImportError: cannot import name LockFile
```
Environment:
```
levente@hontvari-vb:~/selfspy$ lsb_release -d
Description:	Ubuntu 14.10
levente@hontvari-vb:~/selfspy$ python --version
Python 2.7.8
```

More detailed installation instructions would be welcome for those of us, who have no experience with python.
